FROM golang:1.17

COPY ./ ./apisix-seed

RUN if [ "$ENABLE_PROXY" = "true" ] ; then go env -w GOPROXY=https://goproxy.io,direct ; fi \
    && go env -w GO111MODULE=on \
    && cd apisix-seed \
    && make build \
    &&  make install

ENV PATH=$PATH:/usr/local/apisix-seed

ENV APISIX_SEED_WORKDIR /usr/local/apisix-seed

CMD [ "/usr/local/apisix-seed/apisix-seed" ]