version: "3"

services:
  apisix:
    image: apache/apisix:dev
    restart: always
    volumes:
      - ./apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"
    networks:
      apisix-seed:
        ipv4_address: 172.50.238.10

  etcd:
    image: bitnami/etcd:3.4.9
    restart: always
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix-seed:
        ipv4_address: 172.50.238.20

  nacos_no_auth:
    image: nacos/nacos-server:1.4.1
    environment:
      - MODE=standalone
      - JVM_XMS=512m
      - JVM_XMX=512m
    restart: unless-stopped
    ports:
      - "8848:8848/tcp"
    networks:
      apisix-seed:
        ipv4_address: 172.50.238.30

networks:
  apisix-seed:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.238.0/24
          gateway: 172.50.238.1