name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golang-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'

      - name: Download golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.0

      - name: golangci-lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin/
          make lint
      - name: run gofmt
        working-directory: ./
        run: |
          diffs=`gofmt -l .`
          if [[ -n $diffs ]]; then
              echo "Files are not formatted by gofmt:"
              echo $diffs
              exit 1
          fi
