name: unit-test-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - name: run unit test
        run: |
          make test
