name: unit-test-ci

on:
  push:
    branches:
      - refactor/message
  pull_request:
    branches:
      - refactor/message
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'

      - name: startup service
        run: |
          docker-compose -f ci/docker-compose.yml up -d
          sleep 5

      - name: run unit test
        run: |
          make test
      - uses: codecov/codecov-action@v2
